
import controler.MultiploEmail;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JARVIS
 */
public class Integrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Integrar
     */
    public Integrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        banco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tabela = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomeEmpresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailEmpresa = new javax.swing.JTextField();
        servidorEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        senhaLogin = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(980, 620));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Para integrar você deve tem uma base de dados adicionada em Configurações/Banco de dados.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(169, 18, 585, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Com a base de dados adicionada preeêncha os dados abaixo referente ao banco de dados cadastrado.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 44, 626, 15);
        getContentPane().add(banco);
        banco.setBounds(80, 130, 214, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome do Banco :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 100, 103, 15);
        getContentPane().add(tabela);
        tabela.setBounds(80, 240, 214, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nome da tabela :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 210, 103, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nome do campo de Nome :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 320, 163, 15);
        getContentPane().add(campoNome);
        campoNome.setBounds(80, 350, 214, 20);
        getContentPane().add(campoEmail);
        campoEmail.setBounds(80, 460, 214, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nome do campo de Email :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 430, 160, 15);
        getContentPane().add(nomeEmpresa);
        nomeEmpresa.setBounds(430, 130, 457, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nome completo da empresa/plataforma :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 100, 251, 15);
        getContentPane().add(emailEmpresa);
        emailEmpresa.setBounds(430, 230, 457, 20);
        getContentPane().add(servidorEmail);
        servidorEmail.setBounds(430, 430, 457, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Email da empresa :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 200, 113, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Servidor de Email da empresa :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 400, 190, 15);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(807, 527, 81, 23);

        jButton2.setText("Excluir");
        getContentPane().add(jButton2);
        jButton2.setBounds(711, 527, 63, 23);

        jButton3.setText("Pesquisar");
        getContentPane().add(jButton3);
        jButton3.setBounds(594, 527, 79, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Senha de login :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 300, 117, 15);
        getContentPane().add(senhaLogin);
        senhaLogin.setBounds(430, 330, 457, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(banco.getText().equals("") || tabela.getText().equals("") || campoNome.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos de texto!");
        }else if(campoEmail.getText().equals("") || nomeEmpresa.getText().equals("") || senhaLogin.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos de texto!");
        }else if(emailEmpresa.getText().equals("") || servidorEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos de texto!");
        }else{
            MultiploEmail multiplo = new MultiploEmail();
            multiplo.setNomeBanco(banco.getText());
            multiplo.setServidorEmail(servidorEmail.getText());
            multiplo.setNomeTabela(tabela.getText());
            multiplo.setCampoNome(campoNome.getText());
            multiplo.setCampoEmail(campoEmail.getText());
            multiplo.setNomeEmpresa(nomeEmpresa.getText());
            multiplo.setEmailEmpresa(emailEmpresa.getText());
            multiplo.setSenhaEmpresa(senhaLogin.getText());
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField banco;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField emailEmpresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomeEmpresa;
    private javax.swing.JTextField senhaLogin;
    private javax.swing.JTextField servidorEmail;
    private javax.swing.JTextField tabela;
    // End of variables declaration//GEN-END:variables
}
